// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNrVeqhKdW_u25ngRSi4DwVJDdFOh_tjw',
    appId: '1:784643776865:web:f557bbc94fc5c7aab06520',
    messagingSenderId: '784643776865',
    projectId: 'app-music-e8867',
    authDomain: 'app-music-e8867.firebaseapp.com',
    storageBucket: 'app-music-e8867.appspot.com',
    measurementId: 'G-2KYHKKDEPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsQgD_KTJvC-WqAszlZ1qs6NGeulSHoM',
    appId: '1:784643776865:android:73a898525b44cd34b06520',
    messagingSenderId: '784643776865',
    projectId: 'app-music-e8867',
    storageBucket: 'app-music-e8867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYNQW41bGIE8Gv1JVA-t8Uj6I8xUK1OU',
    appId: '1:784643776865:ios:82bba4c214bd3c80b06520',
    messagingSenderId: '784643776865',
    projectId: 'app-music-e8867',
    storageBucket: 'app-music-e8867.appspot.com',
    iosBundleId: 'com.example.applicationMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYYNQW41bGIE8Gv1JVA-t8Uj6I8xUK1OU',
    appId: '1:784643776865:ios:82bba4c214bd3c80b06520',
    messagingSenderId: '784643776865',
    projectId: 'app-music-e8867',
    storageBucket: 'app-music-e8867.appspot.com',
    iosBundleId: 'com.example.applicationMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNrVeqhKdW_u25ngRSi4DwVJDdFOh_tjw',
    appId: '1:784643776865:web:89369899cad5065ab06520',
    messagingSenderId: '784643776865',
    projectId: 'app-music-e8867',
    authDomain: 'app-music-e8867.firebaseapp.com',
    storageBucket: 'app-music-e8867.appspot.com',
    measurementId: 'G-GBVP59FZVQ',
  );
}
